name: Docker Image CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Calculate next version
        id: nextver
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          create_annotated_tag: true

      - name: Build the docker image
        run: docker build . --file Dockerfile --tag devinvideo/qwen-vl-chat:${{ steps.nextver.outputs.new_tag }}

      - name: Docker Push
        run: docker push devinvideo/qwen-vl-chat:${{ steps.nextver.outputs.new_tag }}
